# Generated by Django 5.0 on 2024-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_profile_options_profile_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='perfil', verbose_name='Imagen'),
        ),
    ]
