# Generated by Django 5.0 on 2024-01-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
