# Generated by Django 5.0 on 2024-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_profile_content_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
