# Generated by Django 5.0 on 2024-01-25 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_alter_profile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
