# Generated by Django 5.0 on 2024-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['-created'],
            },
        ),
    ]
