# Generated by Django 5.0 on 2024-01-24 20:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(upload_to='logro', verbose_name='Imagen'),
        ),
    ]
